name: Upload HTML artifact

on:
  push:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/upload-artifact@v4
        with:
          name: project-budget-planner
          path: Project_exercise1.html
